import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT_DIR = process.cwd()
const CONTENT_DIR = path.join(ROOT_DIR, 'content')
const OUTPUT_PATHS = [
  path.join(ROOT_DIR, 'llm-all.md'),
  path.join(ROOT_DIR, 'public', 'llm-all.md'),
]
const DOC_EXTENSIONS = new Set(['.md', '.mdx'])

async function walkDocs(dirPath) {
  const entries = await readdir(dirPath, { withFileTypes: true })
  const directories = entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith('.'))
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))
  const files = entries
    .filter((entry) => entry.isFile() && DOC_EXTENSIONS.has(path.extname(entry.name)))
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))

  const result = []

  for (const file of files) {
    result.push(path.join(dirPath, file.name))
  }

  for (const directory of directories) {
    const childFiles = await walkDocs(path.join(dirPath, directory.name))
    result.push(...childFiles)
  }

  return result
}

function toRoutePath(filePath) {
  const relativePath = path
    .relative(CONTENT_DIR, filePath)
    .split(path.sep)
    .join('/')
    .replace(/\.(md|mdx)$/i, '')

  if (relativePath === 'index') {
    return '/'
  }

  if (relativePath.endsWith('/index')) {
    return `/${relativePath.slice(0, -'/index'.length)}`
  }

  return `/${relativePath}`
}

async function buildBundle() {
  const files = await walkDocs(CONTENT_DIR)
  const generatedAt = new Date().toISOString()
  const docs = []

  for (const filePath of files) {
    const raw = await readFile(filePath, 'utf8')
    const sourcePath = path.relative(ROOT_DIR, filePath).split(path.sep).join('/')
    docs.push({
      sourcePath,
      routePath: toRoutePath(filePath),
      format: path.extname(filePath).slice(1).toLowerCase(),
      raw,
    })
  }

  const lines = []
  lines.push('# llm-all')
  lines.push('')
  lines.push('> This file is generated by `npm run generate:llm-all`. Do not edit by hand.')
  lines.push(`> Generated at: ${generatedAt}`)


  docs.forEach((doc, index) => {
    lines.push('')
    lines.push('---')
    lines.push('')
    lines.push(`## Document ${index + 1}`)
    lines.push(`SOURCE_PATH: ${doc.sourcePath}`)
    lines.push(`ROUTE_PATH: ${doc.routePath}`)
    lines.push(`FORMAT: ${doc.format}`)
    lines.push('CONTENT_START')
    lines.push(doc.raw.trimEnd())
    lines.push('CONTENT_END')
  })

  return `${lines.join('\n')}\n`
}

async function main() {
  const bundle = await buildBundle()

  for (const outputPath of OUTPUT_PATHS) {
    await writeFile(outputPath, bundle, 'utf8')
  }

  process.stdout.write(`Generated llm-all bundle to ${OUTPUT_PATHS.map((item) => path.relative(ROOT_DIR, item)).join(', ')}\n`)
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.stack : String(error)}\n`)
  process.exitCode = 1
})
